CREATE TABLE `deproject-427912.financial_project_de.fact_quarterly_financial`
(
  symbol STRING,
  period DATE,
  assetTurnoverTTM_v FLOAT64,
  bookValue_v FLOAT64,
  cashRatio_v FLOAT64,
  currentRatio_v FLOAT64,
  ebitPerShare_v FLOAT64,
  eps_v FLOAT64,
  ev_v FLOAT64,
  fcfMargin_v FLOAT64,
  fcfPerShareTTM_v FLOAT64,
  grossMargin_v FLOAT64,
  inventoryTurnoverTTM_v FLOAT64,
  longtermDebtTotalAsset_v FLOAT64,
  longtermDebtTotalCapital_v FLOAT64,
  longtermDebtTotalEquity_v FLOAT64,
  netDebtToTotalCapital_v FLOAT64,
  netDebtToTotalEquity_v FLOAT64,
  netMargin_v FLOAT64,
  operatingMargin_v FLOAT64,
  payoutRatioTTM_v FLOAT64,
  pb_v FLOAT64,
  peTTM_v FLOAT64,
  pfcfTTM_v FLOAT64,
  pretaxMargin_v FLOAT64,
  psTTM_v FLOAT64,
  ptbv_v FLOAT64,
  quickRatio_v FLOAT64,
  receivablesTurnoverTTM_v FLOAT64,
  roaTTM_v FLOAT64,
  roeTTM_v FLOAT64,
  roicTTM_v FLOAT64,
  rotcTTM_v FLOAT64,
  salesPerShare_v FLOAT64,
  sgaToSale_v FLOAT64,
  tangibleBookValue_v FLOAT64,
  totalDebtToEquity_v FLOAT64,
  totalDebtToTotalAsset_v FLOAT64,
  totalDebtToTotalCapital_v FLOAT64,
  totalRatio_v FLOAT64,
  CONSTRAINT fk_date FOREIGN KEY (period) REFERENCES `deproject-427912.financial_project_de.dim_date`(date) NOT ENFORCED
);
CREATE TABLE `deproject-427912.financial_project_de.fact_price`
(
  symbol STRING,
  c FLOAT64,
  d FLOAT64,
  dp FLOAT64,
  h FLOAT64,
  l FLOAT64,
  o FLOAT64,
  pc FLOAT64,
  t DATE,
  CONSTRAINT fk_date FOREIGN KEY (t) REFERENCES `deproject-427912.financial_project_de.dim_date`(date) NOT ENFORCED
);
CREATE TABLE `deproject-427912.financial_project_de.dim_date`
(
  date DATE,
  year INT64,
  month INT64,
  day INT64,
  day_of_week INT64,
  week_of_year INT64,
  quarter INT64,
  PRIMARY KEY (date) NOT ENFORCED
);
CREATE TABLE `deproject-427912.financial_project_de.dim_company_info`
(
  symbol STRING,
  country STRING,
  currency STRING,
  estimateCurrency STRING,
  exchange STRING,
  finnhubIndustry STRING,
  ipo DATE,
  logo STRING,
  marketCapitalization FLOAT64,
  name STRING,
  phone INT64,
  shareOutstanding FLOAT64,
  ticker STRING,
  weburl STRING,
  PRIMARY KEY (symbol) NOT ENFORCED
);
CREATE TABLE `deproject-427912.financial_project_de.fact_news`
(
  url STRING,
  summary STRING,
  id INT64,
  source STRING,
  headline STRING,
  image STRING,
  category STRING,
  related STRING,
  datetime DATE,
  symbol STRING,
  CONSTRAINT fk_date FOREIGN KEY (datetime) REFERENCES `deproject-427912.financial_project_de.dim_date`(date) NOT ENFORCED
);
CREATE TABLE `deproject-427912.financial_project_de.fact_yearly_financial`
(
  symbol STRING,
  period DATE,
  bookValue_v FLOAT64,
  cashRatio_v FLOAT64,
  currentRatio_v FLOAT64,
  ebitPerShare_v FLOAT64,
  eps_v FLOAT64,
  ev_v FLOAT64,
  fcfMargin_v FLOAT64,
  grossMargin_v FLOAT64,
  inventoryTurnover_v FLOAT64,
  longtermDebtTotalAsset_v FLOAT64,
  longtermDebtTotalCapital_v FLOAT64,
  longtermDebtTotalEquity_v FLOAT64,
  netDebtToTotalCapital_v FLOAT64,
  netDebtToTotalEquity_v FLOAT64,
  netMargin_v FLOAT64,
  operatingMargin_v FLOAT64,
  payoutRatio_v FLOAT64,
  pb_v FLOAT64,
  pe_v FLOAT64,
  pfcf_v FLOAT64,
  pretaxMargin_v FLOAT64,
  ps_v FLOAT64,
  ptbv_v FLOAT64,
  quickRatio_v FLOAT64,
  receivablesTurnover_v FLOAT64,
  roa_v FLOAT64,
  roe_v FLOAT64,
  roic_v FLOAT64,
  rotc_v FLOAT64,
  salesPerShare_v FLOAT64,
  sgaToSale_v FLOAT64,
  tangibleBookValue_v FLOAT64,
  totalDebtToEquity_v FLOAT64,
  totalDebtToTotalAsset_v FLOAT64,
  totalDebtToTotalCapital_v FLOAT64,
  totalRatio_v FLOAT64,
  CONSTRAINT fk_date FOREIGN KEY (period) REFERENCES `deproject-427912.financial_project_de.dim_date`(date) NOT ENFORCED
);
CREATE TABLE `deproject-427912.financial_project_de.fact_basic_financial`
(
  symbol STRING,
  `10DayAverageTradingVolume` FLOAT64,
  `13WeekPriceReturnDaily` FLOAT64,
  `26WeekPriceReturnDaily` FLOAT64,
  `3MonthADReturnStd` FLOAT64,
  `3MonthAverageTradingVolume` FLOAT64,
  `52WeekHigh` FLOAT64,
  `52WeekHighDate` DATE,
  `52WeekLow` FLOAT64,
  `52WeekLowDate` DATE,
  `52WeekPriceReturnDaily` FLOAT64,
  `5DayPriceReturnDaily` FLOAT64,
  assetTurnoverAnnual FLOAT64,
  assetTurnoverTTM FLOAT64,
  beta FLOAT64,
  bookValuePerShareAnnual FLOAT64,
  bookValuePerShareQuarterly FLOAT64,
  bookValueShareGrowth5Y FLOAT64,
  capexCagr5Y FLOAT64,
  cashFlowPerShareAnnual FLOAT64,
  cashFlowPerShareQuarterly FLOAT64,
  cashFlowPerShareTTM FLOAT64,
  cashPerSharePerShareAnnual FLOAT64,
  cashPerSharePerShareQuarterly FLOAT64,
  currentDividendYieldTTM FLOAT64,
  currentEv_freeCashFlowAnnual FLOAT64,
  currentEv_freeCashFlowTTM FLOAT64,
  currentRatioAnnual FLOAT64,
  currentRatioQuarterly FLOAT64,
  dividendGrowthRate5Y FLOAT64,
  dividendPerShareAnnual FLOAT64,
  dividendPerShareTTM FLOAT64,
  dividendYieldIndicatedAnnual FLOAT64,
  ebitdPerShareAnnual FLOAT64,
  ebitdPerShareTTM FLOAT64,
  ebitdaCagr5Y FLOAT64,
  ebitdaInterimCagr5Y FLOAT64,
  enterpriseValue FLOAT64,
  epsAnnual FLOAT64,
  epsBasicExclExtraItemsAnnual FLOAT64,
  epsBasicExclExtraItemsTTM FLOAT64,
  epsExclExtraItemsAnnual FLOAT64,
  epsExclExtraItemsTTM FLOAT64,
  epsGrowth3Y FLOAT64,
  epsGrowth5Y FLOAT64,
  epsGrowthQuarterlyYoy FLOAT64,
  epsGrowthTTMYoy FLOAT64,
  epsInclExtraItemsAnnual FLOAT64,
  epsInclExtraItemsTTM FLOAT64,
  epsNormalizedAnnual FLOAT64,
  epsTTM FLOAT64,
  focfCagr5Y FLOAT64,
  grossMargin5Y FLOAT64,
  grossMarginAnnual FLOAT64,
  grossMarginTTM FLOAT64,
  inventoryTurnoverAnnual FLOAT64,
  inventoryTurnoverTTM FLOAT64,
  longTermDebt_equityAnnual FLOAT64,
  longTermDebt_equityQuarterly FLOAT64,
  marketCapitalization FLOAT64,
  monthToDatePriceReturnDaily FLOAT64,
  netIncomeEmployeeAnnual FLOAT64,
  netIncomeEmployeeTTM FLOAT64,
  netInterestCoverageAnnual FLOAT64,
  netInterestCoverageTTM FLOAT64,
  netMarginGrowth5Y FLOAT64,
  netProfitMargin5Y FLOAT64,
  netProfitMarginAnnual FLOAT64,
  netProfitMarginTTM FLOAT64,
  operatingMargin5Y FLOAT64,
  operatingMarginAnnual FLOAT64,
  operatingMarginTTM FLOAT64,
  payoutRatioAnnual FLOAT64,
  payoutRatioTTM FLOAT64,
  pbAnnual FLOAT64,
  pbQuarterly FLOAT64,
  pcfShareAnnual FLOAT64,
  pcfShareTTM FLOAT64,
  peAnnual FLOAT64,
  peBasicExclExtraTTM FLOAT64,
  peExclExtraAnnual FLOAT64,
  peExclExtraTTM FLOAT64,
  peInclExtraTTM FLOAT64,
  peNormalizedAnnual FLOAT64,
  peTTM FLOAT64,
  pfcfShareAnnual FLOAT64,
  pfcfShareTTM FLOAT64,
  pretaxMargin5Y FLOAT64,
  pretaxMarginAnnual FLOAT64,
  pretaxMarginTTM FLOAT64,
  `priceRelativeToS&P50013Week` FLOAT64,
  `priceRelativeToS&P50026Week` FLOAT64,
  `priceRelativeToS&P5004Week` FLOAT64,
  `priceRelativeToS&P50052Week` FLOAT64,
  `priceRelativeToS&P500Ytd` FLOAT64,
  psAnnual FLOAT64,
  psTTM FLOAT64,
  ptbvAnnual FLOAT64,
  ptbvQuarterly FLOAT64,
  quickRatioAnnual FLOAT64,
  quickRatioQuarterly FLOAT64,
  receivablesTurnoverAnnual FLOAT64,
  receivablesTurnoverTTM FLOAT64,
  revenueEmployeeAnnual FLOAT64,
  revenueEmployeeTTM FLOAT64,
  revenueGrowth3Y FLOAT64,
  revenueGrowth5Y FLOAT64,
  revenueGrowthQuarterlyYoy FLOAT64,
  revenueGrowthTTMYoy FLOAT64,
  revenuePerShareAnnual FLOAT64,
  revenuePerShareTTM FLOAT64,
  revenueShareGrowth5Y FLOAT64,
  roa5Y FLOAT64,
  roaRfy FLOAT64,
  roaTTM FLOAT64,
  roe5Y FLOAT64,
  roeRfy FLOAT64,
  roeTTM FLOAT64,
  roi5Y FLOAT64,
  roiAnnual FLOAT64,
  roiTTM FLOAT64,
  tangibleBookValuePerShareAnnual FLOAT64,
  tangibleBookValuePerShareQuarterly FLOAT64,
  tbvCagr5Y FLOAT64,
  totalDebt_totalEquityAnnual FLOAT64,
  totalDebt_totalEquityQuarterly FLOAT64,
  yearToDatePriceReturnDaily FLOAT64,
  CONSTRAINT symbol_fk FOREIGN KEY (symbol) REFERENCES `deproject-427912.financial_project_de.dim_company_info`(symbol) NOT ENFORCED
);
