# API Configuration
api:
  key: cmlnl2pr01qmvr47qvs0cmlnl2pr01qmvr47qvsg

stocks:
  - AAPL
  - GOOGL
  - MSFT
  - AMZN
  - NVDA
  - META
  - TSLA
  - V
  - wMT
  - MA
  - JNJ

kafka:
  bootstrap_server: localhost:9092
  topic: finance

gcp:
  path: gs://financial-deproject/ 
